### ISSUE TITLE
Make code more readable

### ISSUE THREAD

**Issue by gridsystem** [Plasso/billing-client-php#3]
This looks like a useful class but there's no good reason for it to be e.g. instantiated with ternary operators as arguments. It looks like you've made it semi-uglified. Why not clean it up so it can be a good reference for users?

**Comment by drewwilson** [comment]
Hey! We did this to make the Client easily "copy-pasteable". We will be releasing the all new Client in the next few days, and it will be fully expanded and have a bunch more stuff in it for an upcoming new product release 👍 Thank you!
